name: Add Cylc

on:
  workflow_dispatch:

jobs:
  add-cylc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Configure git
        uses: cylc/release-actions/configure-git@v1

      - name: Add Cylc
        run: |
          set -x
          sudo gem install bundler
          sudo gem build github-linguist.gemspec
          sudo gem install *.gem
          script/bootstrap
          script/add-grammar https://github.com/cylc/Cylc.tmbundle/
          script/update-ids
          git add -u
          git commit -m '..'
          git status
          git diff
          git push origin HEAD:master
